---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: "Make sure docker is running(?)"
  service: >
    name=docker
    state=started
    enabled=yes
